### ISSUE TITLE
Steve's headshot on About page

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#44]
For some reason I can't get the picture to appear--only the box with the alternate text (at the bottom of the page by his name and title). I saved the image in the Public folder on Google. Can you take a look and let me know what I did wrong? Thanks.

**Comment by matt-cook** [comment]
Ah, I never did show you how to use the images from the folder. The easiest way now will be to append `{{ site.imagefolder }}` before the filename. Like so: `{{ site.imagefolder }}SteveCookCapChapsPic.jpg` in this case, we'll need to size down the image since it's really large. Is that something you are able to do, or should I take care of it?

**Comment by lisa-rieck** [comment]
Thanks, Matt. I can size it down. Did we pick a size for the blog? I can't remember.

**Comment by matt-cook** [comment]
All the blog images are automatically centered/scaled/cropped to 300x170px (though the original images are still downloaded, so it's a good idea to scale them to this size ahead of time to reduce the loading time).

I'd go with 200px max height or width for other content images.

**Comment by lisa-rieck** [comment]
Great. Thanks!
