### ISSUE TITLE
Can't sync my changes

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#52]
Matt,

I uninstalled and reinstalled GitHub for Mac. That seemed to resolve the strange Commit & Sync error that showed someone else's changes and conflicts, and I seem to have your latest versions of files in my desktop folder with the site files.

HOWEVER, any changes I make to those files do not show up on the site, even though the Commit & Sync goes through.

No clue what to do now.

Sarah

**Comment by sarahschilling** [comment]
I just got this email from GitHub after my "TEST Commit & Sync" efforts: 

"The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

If you have any questions you can contact us by replying to this email."

There was nothing listed after "the following error:" so I don't know what the error was. I went to the link supplied above and thought perhaps the errors could be happening because I switched the email address from sschilling@intervarsity.org to sarahschilling@gmail.com (prior to you creating the @corpchaps.com for me). I followed the instructions, but I do not have the "Send verification email" option next to my email address like I'm supposed to.

**Comment by lisa-rieck** [comment]
Yes, I just got the same message when trying to add images to the other 4 blog posts. I also deleted the test posts, but (1) most of the blog category folder disappeared when I deleted the test post, and (2) the test posts are still appearing on the site. And the four new blog images i loaded didn't appear. I'll wait for your direction/help, Matt.

**Comment by matt-cook** [comment]
Finally had a chance to sort this out.  Basically, it's complaining because the same file was edited by two people at the same time. When that happens, it will pop-up the error message when you sync.. then automatically create a "merge" commit that looks similar to:

![merge](https://googledrive.com/host/0B-rUPb5gojEtSTFMU3FPb19yaDA/merge.png)

In the list of changed files, anything tagged 'CONFLICT' has modifications by two people that need to be sorted out manually. 

Git automatically inserts BOTH your content and the other persons content in the file to allow you to manually merge them however you like. The format is like so:

```
<<<<<<< HEAD
  content on server created by another user will be here.
=======
  conflicting content edited by you will be here, below the divider. 
>>>>>>> origin/gh-pages
```

The extra `<<<<`, `=====`,`>>>>>` lines are also inserted to mark the conflicts. These need to be removed when you merge the copy.  If not, you'll probably get "Page Build Failed" errors, or at least funky content. 

If you run into this again, feel free to try and merge the changes yourself.. or let me know and I can walk you through it. The easiest way to prevent this is to sync your changes as frequently as you can, to minimize chances of editing the same file as another person.
