### ISSUE TITLE
404 on start your chaplaincy business

### ISSUE THREAD

**Issue by matt-cook** [capital-chaplains/corpchaps.com#55]

**Comment by sarahschilling** [comment]
Link for Start Your Chaplaincy Business should be: corpchaps.com/get-started/start-your-chaplaincy-business (e.g. no "corporate" in the URL).

I believe I edited the URL for the page awhile back to remove the superfluous "corporate" in the URL because it didn't match the page title name. And, I think I edited the filename to match as well. My guess is this was around the time GitHub wasn't uploading my edits, but perhaps I did it wrong back then. Would you please make this change in the appropriate places?

Other than in the Get Started dropdown, I know this incorrect URL is used in the second link in the description in the main homepage block next to the video.
